# Generated by Django 3.1.6 on 2021-05-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_list_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='share',
            new_name='shared_with',
        ),
    ]
